library("tidyverse")
library("patchwork")
library("here")
library("readxl")
library("bookdown")
library("knitr")
library("kableExtra")
library("BlandAltmanLeh")
library("latex2exp")
library("ggupset")
#library("ggpmisc")
library("boot")
library("rstatix")
library("ggsignif")
library("lme4")
# library("ggstatsplot")
# Maps
#library("rgeos")
#library("maptools")
#library("rgdal")
library("sf")
library("coin")
