library("tidyverse")
library("patchwork")
library("here")
library("readxl")
library("bookdown")
library("knitr")
library("kableExtra")
library("BlandAltmanLeh")
#library("ggpmisc")
library("boot")
library("ggsignif")
library("lme4")
library("ggstatsplot")
# Maps
library( "rgeos" )
library( "maptools" )
library( "rgdal" )
