# Introduction

The economic and ecological value and the importance of feeding mankind by crop pollination of wild bees and the honey bee (*Apis mellifera*) cannot be denied [@kearns1998;@klein2007;@gallai2009]. Managed honey bee colonies improve the quality and amount of harvest for various crops, for example oilseed rape, sunflowers and \textit{Brassica} vegetables [@krause1981;@sushil2013]. An economic market analysis from England showed the value of pollination, honey, and beeswax estimated at £&nbsp;800 per colony in 1992 [@carreck1998]. When the societal benefits of pollination are added, as was done in a study in the U.S., honey bees are estimated to be worth between $1.6 billion and $8.3 billion per year [@southwick1992].Another example from Germany about the economic value for pollination performance in food crop cultivation and net value of honey and wax production was estimated with EUR&nbsp;1.72 billion [@barrios2017]. For the whole of Europe the annual value of the apiculture sector was estimated with EUR&nbsp;one billion and for pollination EUR&nbsp;22 billion per year [@commission2014]. There may be a lot more benefits which are often overlooked or simply not well enough researched, for example the bee colonies fertilizing effect of bee frass in foraging areas, which at least under study control did show a significant release of inorganic nitrogen into the soil [@mishra2013]. Or their participation in the food chain as important nutrient source for predators, as such the bee-eaters (Meropidae) with an average 15-25% of honey bees in their diets [@fry1983]. Bee-eaters feed in addition on pests which makes them beneficial for agriculture and maybe even for apiculture itself [@fry1983]. Nevertheless, @southwick1992 made it clear in their discussion that we do not only profit from honey bees, but also from wild pollinators and should improve their environment and create conservation zones. These examples about the importance of insects makes the alarming decline of wild pollinators over the last years even more catastrophic for us and the ecosystem [@hallmann2017;@sanchez-bayo2019]. The reasons for the decline seem manifold: parasites; pathogens; environmental pollution; rapid climate change, loss of insect friendly habitats etc. [e.g. @biesmeijer2006;@potts2010;@goulson2015;@woodcock2017].
<!--Even though we learn each day more about the importance of insects in our ecosystem an alarming decline of wild pollinators can be seen over the last years [@hallmann2017;@sanchez-bayo2019]. --> 

With the economic and ecological value of honey bees in mind I want to look at the expenses and treatment effectiveness of *Varroa* mite control methods in Austria. The *Varroa* mite, *Varroa destructor*, is worldwide, with some exceptions, an active threat to apiculture [e.g. @dahle2010;@rosenkranz2010;@genersch2010;@morawetz2019;@noel2020;@roth2020]. Varroosis, the disease caused by *Varroa* mites, is one of the most frequently observed honey bee disease in Austria. It is related to a high *Varroa* mite infestation and does increase the risk of colony losses [@morawetz2019]. Although, colony losses are not only caused by *Varroa* damage, the financial loss of lost and weak colonies is substantial for the apiculture sector [@popovskastojanov2021]. In addition for beekeepers the *Varroa* pest led to an increase in costs in labour, material expenses on treatment and replacement of lost colonies [@nationalresearchcouncil2007;@vanengelsdorp2010a]. In the US, were pollination services are a big industry for beekeepers, the spread of *Varroa* mites and colony collapse disorder (CCD) did came at the same time as higher prices paid by farmers for pollination services [@carman2011;@rucker2012]. This indicates in a real world example that the introduced *Varroa* mite and colony losses do not only impact beekeepers but also the food production industry and shows the importance of pollination services of insects [@kearns1998;@klein2007;@gallai2009].

In Austria, as in most other central European countries, beekeepers had to cope with this imported aggressor since the 1980s [@griffiths1981;@potts2010a]. In Germany a small scale survey did show that pests are perceived as the main challenges for beekeepers followed by poor landscape for foraging due to monocultures [@barrios2017]. Beekeepers need to treat their colonies to prevent the unacceptable levels of colony losses, as most untreated colonies would die off within 2-3 years [@rosenkranz2010]. The first years after the mite domination in Europe and the resulting treatment effort, in combination with other socio-economic, factors may have led to a sharp decline in beekeepers [@potts2010a;@brodschneider2011]. Although in Austria, the number of beekeepers and honey bee colonies has been steadily growing over the past 7 years.[^biene-österreich] The control of the mite in Austria is mainly done with organic acids (e.g. formic acid, oxalic acid), essential oils (thymol) or biotechnical methods and less often with synthetic acaricides [@oberreiter2020]. Each of these treatment methods has its advantages and disadvantages and most of the time beekeepers use a combination of them [@rosenkranz2010;@noel2020;@oberreiter2020]. Though the treatment alone does not guarantee the survival of colonies, studies show that the education, experience, and correct application and timing of treatment play an important role [@brodschneider2013;@vanderzee2014;@jacques2017;@morawetz2019].

Additionally, I want to look at the main motivations for choosing a treatment method. This empirical approach to evaluate the motivations behind management practices against *Varroa* mites has never been done before, to the best of my knowledge. Somewhat similar studies from the U.S. did identify different types of philosophies in management practices [@thoms2019;@underwood2019]. The focus of these studies was quite novel to the already rich literature on most topics in beekeeping. As the U.S. is quite different in its beekeeping structure, it is important to create similar socio-ecological studies in Austria.

In the foreground of this work is an exploratory analysis of a citizen science survey from the winters 2018/19, 2019/20, and 2020/21. The survey has been carried out since 2008 by the Institute of Biology at the University of Graz to collect data on winter losses of managed honey bee colonies [@brodschneider2013]. In the past three years, the participants could also answer an optional question about their expenses of treatment per honey bee colony, without labour costs, and in the last year, an additional question about why they chose their *Varroa* control methods was added. These two questions are the main focus of this study, as such a descriptive analysis of treatment expenses in combination with their effectiveness and motivational reasons has never been carried out in this form before. Furthermore, the selected treatment methods and their efficiency, based on reported winter colony losses, are compared in combination with their expenses to give valuable input for beekeepers in their decision-making process.

[^biene-österreich]: Austrian beekeepers federation 'Biene Österreich' \url{https://www.biene-oesterreich.at/}, accessed: 12/2020.
<!--A Federation refers to a group of states, organizations or other legal entities. An Association, in contrast, refers to a group of people or groups of people uniting for a common purpose.-->