# Discussion

## Sample Representatively and Limitations

Although the popularity and rise of new beekeepers in Austria, a decrease in absolute and relative numbers of participants over the three survey years was observed (Table&nbsp;\@ref(tab:registered)). I would have expected the opposite because in 2016 new rules made it obligatory for beekeepers who want to participate in the bee health program to fill out the annual winter loss survey. Beekeepers who are part of the bee health programme are allowed to apply and/or receive a higher rate of government aid for investments in technical equipment to improve production quality and hygiene in their beekeeping operation.^[AgrarMarkt Austria, 06/2021 - Version 04] Before this indirect monetary incentive there were no advantages or personal rewards for participants in the voluntary survey. Incentives showed in an analysis of two meta-studies an increase of survey responses and also a lower drop-out rate. However, the effect or higher motivation due to incentives is comparatively small [@goritz2006;@bruggen2011]. One of the strong major motivations for beekeepers to participate in citizen science ecological field studies is to be able to contribute to the scientific knowledge [@gratzer2021]. The high rate of participants with intrinsic motivation was also identified for online surveys [@bruggen2011]. The winter colony loss survey cannot be described purely as a citizen science study or an ordinary online survey and is likely an in-between [@brodschneider2022]. Nevertheless, to increase and improve the retention of participating beekeepers, the project should strive for better communication on how it improves the beekeeping knowledge [@nov2014]. An idea to increase the personal benefit for the participants would be a personalized automated report of the survey results, were the independent results are compared to the total observed results. This could be perceived as an acknowledge service in the form of a free professional data analysis for the volunteers, which is one of the motivations for citizens scientists [@gratzer2021].

As with the majority of monitoring survey studies, the design is subject to limitations especially in their representativeness. From a statistical standpoint, we cannot say our sample represents the beekeeping population in Austria as the sample was not selected at random [@vanderzee2013]. In Austria all beekeepers must officially register in VIS[^r-vis], but access to this data is limited and only available for prevention of diseases. A random stratified selection out of all beekeepers would be an ideal situation, which would help to prevent potential selection biases and survey errors [@heeringa2010;@vanderzee2013]. With this in mind the survey results and point estimates should be viewed with caution. In any case, the participating beekeepers in the survey are from close to all country districts, indicating a thorough spatial coverage, and an adequate response rate of 3.5-4.0% summarises to around 1,000 participants each year. In this study there could be a bias towards younger or more technical versed beekeepers as only the online survey did include the questions on expenses and motivation, removing around 10% of participants.

Based on the rules of thumbs from @roscoe1975, a multivariate analyses should typically comprise 10% more responses than questions and cover all answering groups with an appropriate number of answers (*n*=30). The problem of low sample sizes in certain categories of the survey with multiple possible answers can somewhat be opposed with the data collection over three years. Consistent results can be viewed as more robust and reduce the probability of mistaken inferences in statistics or weak if they vary between the years. Although, changes in results could stem from interactions with temporal effects as for example the weather, which has shown to impact the winter colony survival [@switanek2017;@becsi2021]. The reported inference based statistics are without correction of the alpha error, since different hypotheses are tested in the questionnaire as it is mostly explorative and possible overlaps of the hypotheses are difficult to classify. In addition for permutation tests, which were used in the two level factor analysis (Section \@ref(two-level)), the combination of skewed data and unequal sample sizes could lead to possible false inferences [@christensen2021]. As I do not rely on the *p*-value alone and to reduce the effect of skewed data the less powerful rank based permutation test was chosen with a bootstrap confidence interval. The advantage is that it also allows me to visualize the statistical test results in a meaningful way. Methodically a lot of care was undertaken to identify outliers and the imputation of some answers. For good practice and to minimize arbitrary decisions different statistical methods were applied and the gained knowledge from desk research estimation of expenses was taken into account [@kwak2017]. However, this imputation, which can be seen as an act of data manipulation, should not be taken too lightly. With my methodical transparent approach and the public availability of the source code I try to take care of possible arguments of manipulative intentions. The questionnaire itself should anyway be seen as a helpful tool to identify possible risk factors and compare the results in a standardised way with other countries part of COLOSS [@brodschneider2016;@brodschneider2018].

Another point which may represent a limitation is the survey data quality. Especially for the question about estimated treatment expenses per colony without labour costs. The data distribution showed participants mostly answered in full round numbers, e.g. 5 or 10 Euro. Beekeepers answering on this question without ordinary estimates would need to keep books on their expenses or invest more effort when answering the survey, to find out how much they actually spend. I believe this is not the case for the majority, as most participants presumably regard beekeeping as a hobby and do not keep track of their expenses. Additionally, the position of the question in the questionnaire could cause a negative effect as it placed at the end of the survey. Although the structure did not seem to portray a major role on data quality as shown in a postal survey [@dunn2003].

## Motivation choosing *Varroa* Control Method

The motivation why participants practise a specific method was a novel question and was only asked in one survey year. 'Efficacy' (67.3%) which was picked by the majority, as one of the categories, is the most relevant factor. The obvious follow up question would be, how do the participants know that their chosen control method is effective. In Austria the treatment methods are dominated by organic acids and the loss rates for these methods are similar [@oberreiter2020]. The majority follows the official recommendation by the Agency for Health and Food Safety (AGES) of formic acid after honey harvest in summer and oxalic acid treatment in winter [@moosbeckhofer2015]. In comparison to Czechia, which showed in four successive winters lower loss rates than Austria, synthetic acaricides are common (e.g. Amitraz) and can even be commanded by the authorities if the *Varroa* infestation level is unacceptably high [@brodschneider2019a]. Even though synthetic acaricides show a specificity and effectiveness against the *Varroa* mites, residues and resistances remain a problem [@rosenkranz2010;@noel2020]. For example coumaphos as acaricide against *Varroa* mites does show high levels of residues in bees wax after one treatment [@kast2021]. In the survey the motivation category 'Residues' (42.9%) is the third most picked category, showing that the participants are aware of the problem. Especially for bigger beekeeping operations this category is very important and was the second most. 'Resistances' was selected by only 17.1% and seem for most not a primary motivation for choosing their *Varroa* control method but again it is more of a concern or motivational reason for bigger operations in Austria (28%). The high concern or possible knowledge of 'Residues' and the awareness of 'Resistances' could be the reason, why compared to the treatment strategy in Czechia or the common practices of side-line and commerical U.S. beekeepers, the use of synthetic acaricides is rather low in Austria [@underwood2019;@brodschneider2019a]. The problem of resistances with synthetic acaricides can furthermore be minimized by employing different synthetic agents in each year [@tihelka2018;@noel2020].

The total second most picked category in the survey represent 'Side effects on bees' (49%). Somewhat similar, a desire for high standards for farm animals was identified in a survey in young people in agricultural and forestry schools in Austria [@kirner2021], showing the importance of animal welfare in agriculture for young people. Dependent on the treatment method, synthetic acaricides, organic acids or thymol products do have various negative side effects on bees [@tihelka2018]. Probably all treatment methods can have side effects on honey bees, but research on this topic is not available for all products. For example the accumulation of the synthetic acaricide coumaphos in the bees wax can lead to toxic levels for larvae [@kast2020]. The organic formic acid treatment is highly dependent on outside temperature and the fumes can damage adult bees and larvae [@bolli1993;@underwood2003]. In addition various treatment methods showed under controlled conditions negative influence on the gene expression for memory of adult honey bees [@gashout2020] and overdoses of oxalic acid trickling in winter can lead to higher bee mortality [@charriere2002;@adjlane2016]. As the category 'Side effects on bees' were so commonly picked but formic acid is still very common, I believe that beekeepers want more knowledge and research about sublethal effects of treatment methods and possible alternatives or ways to minimize the side effects. Without doubt the best treatment would be if no treatment at all are necessary, but so far honey bee colonies selected for their adaptational traits against *Varroa* mites are only local phenomena [@mondet2020a;@mondet2020;@guichard2020].

Participants most common sole answer was 'Recommendations from beekeeping associations, extension workers, veterinarians, magazines, etc.' (*n*=16), which was picked in total as one of their up to five choices by 26.1%. It is only a small motivational factor for bigger operations with around 10% but was triple as often selected by 'Recreational Beekeepers'. This means that around one-third of small scale beekeepers in our survey are motivated by external resources in their decision making. This demonstrates the importance of knowledge transfer and dissemination of scientific results in the beekeeping community and of projects like B-RAP from COLOSS, which tries to improve the information flow between beekeepers and scientific results and vice versa [@brodschneider2022;@kristiansen2022]. For example the communication of ways for integrated pest management (IPM) or integrated *Varroa* control in beekeeping could be fruitful as it would be one way to measure 'Efficacy', lower 'Residues' and 'Side effects on bees' and minimize the chance of 'Resistances' [@roth2020;@bubnic2021].

Only a small amount of beekeepers are picking their treatment methods purely from 'Habit' (10.8%), showing that beekeepers are somewhat flexible and willing to change their methods. An U.S. national survey identified two main groups of beekeepers in their *Varroa* management beliefs, the first one 'Treatment Skeptics', which were less likely to treat and 'Treatment Adherents' who actively try to keep bees healthy [@thoms2019]. The authors discuss further that communication needs to be adapted to these two beliefer-types and beekeepers should be made aware that their decision in management practices also influences neighbouring colonies to prevent upcoming conflicts between the groups [@thoms2019]. In our survey we can see clearly two different goals and motivations for selecting *Varroa* treatment methods based on the operation size. Motivations on some issues, e.g. 'Efficacy', overlap but on others are quite different, e.g. 'Residues' or 'Recommendations'. The differentiation was to be expected, as the individual management practices and goals need to be adapted when handling more colonies. This continuum of management practices as described in a study from the U.S. shows that philosophy and management for commerical and sideline beekeepers compared to backyard beekeepers differ significantly [@underwood2019].

Interestingly the category 'Economic Costs' was only picked by 6.4% of the participants, showing that expenses are only a low motivational driver for choosing a specific method. @thoms2019 showed in their U.S. survey that 'Money' was reported as one of the main disadvantages of managing *Varroa* mites at fourth place after 'Kills, weakens, or hurts bees', 'Chemicals in colony' and 'Time'. As most beekeepers in Austria are hobbyists, it is apparently of no surprise that economic reasons are no major motivation factor for keeping bees and the expenses for treatment against *Varroa*, even though some can be substantial, are probably low in comparison to other expenses, e.g. sugar for feeding or production costs of hives. That the economic related categories are more of a motivational factor for bigger operations (>25 colonies) can also be seen in the results, as the categories 'Economic Costs' (9.0%) and 'Time and number of applicants' (29.0%) were more frequently chosen among those.

The two least chosen motivations 'Others' (0.5%) and 'Marketing' (0.2%) tell us that the selected 21 categories are complete and beekeepers in Austria are probably not influenced or seldom come conscious into contact with advertisement for treatment methods. Although advertisement as such could also be hidden as recommendation in presentations or articles.

## Data Distribution and Estimation 

The non-normal distribution of reported treatment expenses per colony with a mean of EUR&nbsp;11.4 and median EUR&nbsp;10 was expected, because costs for the different treatment methods in investment, material and consumables vary (Fig.&nbsp;\@ref(fig:distr-year)). Although not directly comparable, similar values to the Austrian average can be seen overseas in the annual apiculture monitoring report from New Zealand. In this report the *Varroa* treatment expenses per hive are estimated with NZD&nbsp;14-19 (EUR&nbsp;8-11[^exchange-nz]) [@mpi2020]. In an U.S. research about the pollination markets they went with an approximating of USD&nbsp;18 per colony for treatment consumables and application costs [@rucker2012]. Adjusted for inflation since 2002 this would be nowadays USD&nbsp;27 which are converted EUR&nbsp;23.9.[^exchange] This estimate likely additionally includes the labour costs in application, which was not the case in our survey. On that note a survey from Albania showed that acaricides only account for a minor percentage of the production costs for honey and drug treatment in general did account on average for 5% of the total work load in beekeeping operations [@dedej2000]. Sadly the researcher did not report the data in sufficient manner to extract more information. Similar values were found for a EU wide survey with 41% of the beekeepers reporting that *Varroa* control does make up between 0 and 10% of their production costs [@commission2014]. Nevertheless, compared to the loss when colonies do not survive the winter, which was estimated with EUR&nbsp;318 in Austria [@popovskastojanov2021], the treatment expenses purely on an economic standpoint are rather worthwhile. At least if the treatment method is also effective enough to prevent colony losses due to *Varroa* mites. Furthermore, this is only the direct economic loss for the beekeeper, as the indirect socio-economic loss is even higher due to honey bees important activity as pollinator for our food supply [@southwick1992].

As there are no previous market analyses or pilot studies in Austria, I implemented the calculated estimates to successfully validate the survey results for plausibility (Table&nbsp;\@ref(tab:table-estimates)). The overlap of survey responses and estimated expenses, despite the fact that they are on average similar, to show some differences when looking at the different survey treatment method combinations. One of these overestimations are the combinations including 'Another Biotechnical Method', excluding the separately asked methods 'Hyperthermia' and 'Drone brood removal'. One reason for the wrong estimation is probably because the method itself includes a broad range of applications with different expenses and the mean value only represents one point. For example the less expensive small plastic clip for queen caging compared to the more expensive full frame stainless steel cages. Another reason could be the more sophisticated calculation in the estimate of the yearly depreciation of investment and material costs which may result in differences to the survey, as this economically way of calculation is probably not done by the majority of participating hobbyist beekeepers. The underestimation of the two formic acid treatment methods without any winter treatments could be due to the application frequencies, as in the estimate I only calculate one application per month. Additionally, we only compared in this case the arithmetic mean expenses. Which is influenced by outliers as shown by the far off underestimated treatment combination of summer and winter oxalic acid trickling of ready-made mixture. Although a lot of care was taken in data cleaning and validating before the analysis, this is one of the reasons why only treatment method combinations with at least 30 answers in the efficacy and economical section were further analysed and mean with standard deviation and median are reported. 

[^exchange]: Calculation date: 13th December 2021. Inflation based on Consumer Price Index (CPI) with 50.62% since 2002. Conversion with exchange rate published by central banks 1&nbsp;USD&nbsp;=&nbsp;0.886682&nbsp;EUR.

[^exchange-nz]: Calculation date: 5th January 2022. Conversion with exchange rate published by central banks 1&nbsp;NZD&nbsp;=&nbsp;0.6041&nbsp;EUR.

## Extrapolation

The *Varroa* treatment agent market was to my knowledge never before estimated for a country. The total market value increased with the growing number of colonies registered in Austria over the three survey years. In total value, as a rough extrapolation, this sums to EUR&nbsp;2.9 to 4.8 million per year in Austria or per 100.000 honey bee colonies to EUR&nbsp;0.8-1.2 million. If one would use this calculation on the approximated 19 million honey bee colonies in Europe in 2020[^fao], this would equal to EUR&nbsp;147-225 million. For Europe this rough estimate is probably off as the countries differ in their preference for treatment methods, and most colonies are treated with amitraz strips or fumigation [@brodschneider2022a]. As for the calculation of the extrapolation, two different methods were used. The arithmetic mean as one method, which is influenced by high outliers and the geometric mean as second, which may underestimates as it is higher influenced by lower values. Nevertheless, the extrapolation shows a possible economical burden for Austrian beekeepers and on the other hand the economical value of the agent market, both as direct impact of an introduced aggressor since its extend into Europe in the 1980s [@griffiths1981;@potts2010a]. Compared to other arthropods invasive in Europe, *Varroa destructor* is one of the most harmful neobiota and does have the highest negative economical impact [@vaes-petignat2014]. 

[^fao]: Food and Agriculture Organization of the United Nations. FAOSTAT statistical database, accessed 28th June, 2022.

My calculated value does not even account for the hours of labour, which each treatment method requires. Nevertheless, the extrapolation of expenses for treating against *Varroa* mites are overshadowed if compared to the national economic losses due to colony losses and weak colonies, which was estimated with EUR&nbsp;32 million in 2016/17 for Austria [@popovskastojanov2021]. As a matter colony losses are not alone caused by *Varroa* mites, but comprise of a combination of multiple abiotic and biotic factors [@neov2019]. In addition how many colonies losses are prevented by the active *Varroa* treatment is unknown in Austria. Even so, an acute degree of *Varroa* infestation is correlated with multiple negative effects on the honey bee colony and their individuals and in the worst case it can lead to their death [e.g. @rosenkranz2010;@noel2020;@morawetz2019;@traynor2020].

## Operational Factor Analysis

Of the three selected operational questions, the highest difference in the two levels factor analysis was between the two defined operation size groups. With small beekeeping operations with 25 or less colonies, which can be seen as 'Recreational Beekeepers', spending on median between EUR&nbsp;4 and 5 more than the bigger operations with more colonies. These two groups are uneven split up in their sample sizes, with far the most of our survey participants belonging to the 'Recreational Beekeepers' group. The survey distribution very likely reflects the real population distribution for Austria, but cannot be verified. In addition the low rate of professional beekeepers can be seen throughout most European countries [@chauzat2013;@commission2014;@barrios2017]. As for winter colony losses it was shown before that bigger sized operations are loosing less colonies with professionalism as one of the explanation [e.g. @lee2015;@brodschneider2018;@gray2020]. The reasons for lower losses and expenses could be in their different management practices of their colonies, as bigger operations are financially driven and and their goals are probably more economical [@underwood2019]. Additionally some investments are relatively more expensive for smaller operations, as you can only use them for a smaller number of colonies, e.g. sublimation tools for oxalic acid. 

As for the other two operational factors, migratory beekeepers and certified organic beekeepers are spending less than the corresponding counterparts. This may be partly explained by the interaction of these groups and their operation size (Fig.&nbsp;\@ref(fig:distr-groups)). But the results show that the third and fourth most common operational group combinations in our survey are 'Recreational Beekeepers' (<= 25 colonies) which are certified organic or migratory beekeepers. Indicating that these two groups are not dominated by the bigger operations and therefore lowering the interaction influence. Running a migratory and/or organic beekeeping operation probably comes with more financial considerations. This could lead to a more economical colony management. Furthermore, both operational factors are probably an indicator for experience and expertise, which is also believed to be one of the main reasons for lower colony losses [@lee2015;@underwood2019;@oberreiter2020]. @underwood2019 showed in their beekeeping management study in the U.S. that organic beekeepers tend to use biotechnical and alternative treatment methods. One example for a biotechnical method with low treatment material expenses is the total brood removal (TBR), but only if one does not account for time investment [@mancuso2020].

<!--On this note, the difference in expenses in the two levels for the two operational factors is lower than the operational size and in the multiple regression model the effect is too small to be of significant impact. -->

## Multiple Regression

The accuracy of the selected factors in a simple multiple regression model for estimating the expenses per colony is rather low. If the only goal is to predict the expenses, adding additional features from the survey and using a more sophisticated method like Machine Learning, which could also be used to refine the exploratory results, could be a viable future option. In prediction models the weight and value of individual predictors are less important, as the purpose lies in the correct prediction and not in explaining the causal mechanisms behind the results [@buskirk2018]. The advantage of the selected linear regression model is that it can accommodate both prediction and explanation, with focus on simplifications of the independent variables. The selected predictors and their individual influence on the outcome can be statistically quantified and possible relationships explored [@buskirk2018].

The two operational questions 'Certified Organic Beekeepers' and 'Migratory Beekeeper' as additional covariates did only have a small explanatory value if combined with the reported number of colonies. The two factors were previously discussed and analysed in the operational factor analysis by themself, where they already showed lower differentiation in expenses as compared to the difference between the defined operation size groups. The model now incorporates a finer resolution of the number of colonies, which possible explains even better the difference in expenses than the categorical operation size groups. Additionally, the defined range for 'Recreational Beekeepers' with one to 25 colonies is rather wide, it would be plausible to find some types of overlapping correlations between operation size and operational questions on a smaller scale. For example, I would expect beekeepers with only a few colonies to not migrate and not to be certified organic. This may explain the low gains by adding these covariates to the model.

The selected best model includes the treatment methods and operation size. The methods 'Synthetic Methods', 'Hyperthermia' and 'Thymol' do increase on average the expenses the most. These products are more expensive compared to organic acids as consumables or for 'Hyperthermia' in investment. In my estimation 'Thymol' was also identified as the most expensive consumable on the market. Furthermore, it is not only expensive but the efficacy in field is also questionable, as seen in a world wide survey were around 40% of the beekeepers did rate thymol treatment as insufficient [@mezher2021]. Interesting is that 'Another Biotechnical Methods' is the only treatment method which reduces the estimated intercept if applied. One example would be the total brood removal (TBR), as already given in the operational factor section, which leads to lower treatment expenses upfront but possible high feeding costs, resulting in substantial total expenses per colony of 26 to 45 Euro, as shown in a recent European study [@mancuso2020]. In addition these methods are often labour intensive, which shows the need for more time budget studies. From the three different available oxalic treatment options the 'Oxalic acid - sublimation' did increase the estimate the least, showing that it is a less expensive option compared to the ready-made mixture or pure trickling or spraying methods. Although, the investment of sublimation tools is more expensive, it can be used over multiple years and for multiple colonies and the low amount of oxalic acid needed may offset the investment quickly. On the efficiency side the sublimation of oxalic acid showed in field studies better results compared to trickling [@altoufailia2015]. The same trend of low expenses for 'Another Biotechnical Methods' and 'Oxalic acid - sublimation' can be seen in the next discussed effectiveness and economical section.

## Effectiveness & Economic

In Austria it is most common for beekeepers to apply organic acids (e.g. formic acid, oxalic acid) as *Varroa* treatment, whereas oxalic acid is more or less the sole option for the last treatment in winter as shown in the network analysis (Section \@ref(network)) and as published previously [@oberreiter2020]. Alternative for example synthetic methods do exist, but are only applied by a minority, compared to other European countries where synthetic acaricides are frequently used, e.g. France, Spain, Romania [@brodschneider2022a]. In general each method has their own strengths and weaknesses and some are more dependent on outside environmental conditions like temperate or humidity [@rosenkranz2010;@noel2020]. The multiple year approach allows to identify the effectiveness of treatment methods. Nevertheless, the interpretation of the results are on point estimates but confidence intervals for loss rates are mostly overlapping between the analysed treatment combinations. The same is true for the expenses per colonies, as the variation is high and low sample size for some treatments results in wide standard errors.

The most common treatment combination over the three years of survey was long term formic acid treatment in summer followed by oxalic acid trickling in winter (**A** 'SU-Fa-LT & WI-Ox-pure'). A treatment with formic acid and oxalic acid is the national recommendation for Austrian beekeepers by the Agency for Health and Food Safety (AGES) [@moosbeckhofer2015]. The combination showed on average consistently low and intermediate loss rates but high expenses compared to other treatment combinations. Formic acid evaporation is known to be an effective treatment variant with a low risk of residues or resistances [@rosenkranz2010;@noel2020]. The long term treatment shows a better effectiveness compared to to the short term formic acid treatment with the same combination (**E** 'SU-Fa-ST & WI-Ox-pure'), but the short term treatment is less expensive. The difference in effectiveness was already observed in Austria in a previous study [@oberreiter2020]. Although effective, formic acid has multiple disadvantages as it is dependent on outside temperature and humidity and can have considerable negative impact on the health of honey bees in high concentrations [@bolli1993;@tihelka2018;@underwood2003;@noel2020]. The long term evaporation of formic acid is typically used with applicators (evaporators) designed for a more controlled release of the fumes due to smaller exposure area, resulting in slower and longer release and maybe better effectiveness [@underwood2003]. The disadvantage of the short term formic acid treatment in summer could be minimized when used in combination with sublimation of oxalic acid in summer and winter, as it did show promising results in both effectiveness and economically (**J** 'SU-Fa-ST & SU-Ox-sub & WI-Ox-sub'). A more expensive but with consistently low loss rates is the combination of long and short term formic acid in summer with oxalic acid sublimation in summer and winter (**O** SU-Fa-ST & SU-Fa-LT & SU-Ox-sub & WI-Ox-sub). One of the least effective and more expensive treatment method was the single application of formic acid long term treatment in summer (**M** 'SU-Fa-LT'). This shows that only a single treatment in summer is not enough and a treatment in winter is needed or at least needs to be evaluated. At best IPM strategies should be employed to minimize acaricide input and evaluate the success of treatments [@roth2020;@bubnic2021].

A treatment combination without formic acid and good economic value was the oxalic acid sublimation in summer and winter (**F** 'SU-Ox-sub & WI-Ox-sub'). It was categorized in each year as low expense treatment and showed low to intermediate loss rates. In the multiple regression model the sublimation variant did increase the expenses the least of the oxalic acid treatment methods. As for effectiveness, in a study on different oxalic acid methods the sublimation did perform better than the trickling or spraying application [@altoufailia2015]. In this regard oxalic acid does only work effectively in broodless periods [@rosenkranz2010;@noel2020]. Therefore, I expect that beekeepers performing oxalic acid sublimation in summer repeat it multiple times to be effective or in combination with biotechnical methods. But I do not have any more information on the frequency or colony conditions in which it is applied.

One way to minimize the amount of acaricides is with biotechnical methods. These combinations, without drone brood removal or hyperthermia because they are treated separately in the survey, were on average more economically than formic acid treatments. The effectiveness did vary between the years and the methods were categorized as low but also as high loss combinations. Previous studies in Austria showed that the biotechnical methods in summer, in direct comparison to the beekeepers who don't use these methods, resulted in significant lower observed loss rates [@crailsheim2018;@oberreiter2020]. Biotechnical methods with long term queen caging does also seem to have no negative impact on the queen health [@buchler2020]. Disadvantageously is that the methods are often labour intensive and the positives effect of being more economically without labour costs could be diminished if one accounts for time spend on manual labour [@rosenkranz2010;@buchler2020]. @mancuso2020 evaluated annual data from beekeeping operations and showed that various biotechnical methods (total brood removal (TBR), queen caging (QC), royal cell (RC)) lead to high investment of manpower (minutes/colony) with a range from 30 to 83 minutes compared to chemical methods with only 19 to 29 minutes per colony. In addition the TBR method lowered honey production and increased expenses per colony mainly because more feeding is needed. Despite these an increase of revenue for operations using TBR was observed because of organic quality bee products and possible side income from nucleus sales [@mancuso2020]. In a wide scale european study the average time for summer treatment with queen caging and followed by oxalic acid trickling was estimated with 20 minutes per colony [@buchler2020]. On effectiveness the usage of biotechnical methods showed in field studies promising results and can be seen as a good alternative to organic acid or synthetic treatment and as an addition for integrated pest management (IPM) [@lodesani2019;@buchler2020;@mancuso2020]. In our survey a problem to evaluate the biotechnical methods is that this category by itself contains a multiple of different techniques and approaches, which makes it difficult to analyse. 



