# Conclusion

The total economic burden by the introduced aggressor *Varroa destructor* on beekeepers is substantial. This study gives a first estimation and extrapolation of the treatment expenses for beekeepers in Austria and analyses a small fraction of this burden which already sums to a few million Euros on a national scale. The motivations why beekeepers choose their treatment methods showed a high interest in the honey bees well-being as 'Efficacy', 'Side effects on bees', and the awareness of problematic 'Residues' were top priorities. It also showed a difference in goals and beliefs for smaller recreational beekeepers, who depend more on external information and are less motivated by time or costs, which is more important for bigger operation who are more economically driven. 

In Austria the dominance of organic acids as treatment method is probably also a reflection of their motivations. Single treatments in summer with formic acid showed once again not enough efficacy on average. The most common treatment combination of formic acid long term in summer and oxalic acid trickling in winter results in consistently low loss rates. A treatment combination which can be recommended based on the results is the oxalic acid sublimation in summer with formic acid short term and followed by oxalic acid sublimation in winter, as it showed consistently low loss rates and low expenses. Without labour costs the uptake of biotechnical methods seems to be economical and depending on the method maybe less harmful for honey bees with no risk of residues or resistances, although effectiveness was variable. The reduction of pesticides should be a main goal, in which biotechnical methods can help [@buchler2020]. As the treatment against *Varroa* mites is a dominant topic in beekeeping since over 40 years in Europe, a lot of effort and time is invested by breeders and scientists to select for honey bees who can defend or live with the mites without treatment, but so far without any major adaptation or success [@mondet2020a;@mondet2020;@guichard2020;@bubnic2021]. The economic way of beekeeping with a high density of colonies and swarm reduction techniques will probably always rely on active pest control. Nevertheless, directed natural selection may be a solution to keep healthier honey bee colonies [@seeley2007a;@locke2016;@neumann2017;@oddie2021]. This phenomenon is already observed in several honey bee populations in Europe which actively hinder the *Varroa* mite in its development through their behaviour and they may also exist in Austria [@mondet2020;@oberreiter2021].

The uncertainly range of the results and the effort put into data cleaning did reveal some disadvantages of our survey. An alternative approach for evaluating the economic values or impact would be to work more closely with beekeeping operations for a thorough result. This was done for example in a detailed economic breakdown of honey bee queen breeding in Canada [@bixby2020] or in an economic evaluation of biotechnical methods [@mancuso2020]. Although, the advantages of the already existing survey are probably higher, e.g. using an already established survey and getting more answers in addition to lower workload and costs to get the data. Additionally my thesis is showing the importance of ongoing surveys to evaluate and observe trends and changes in the beekeeping community. For the beekeepers the results are information of their peers and for national beekeeping clubs and politics the results can be used to find out more about the needs in the beekeeping community and to help in their political decision-making. 
