Für deine MA Results: 12 Teilnehmer haben mehr als 5 Antworten gegeben, und diese wurden entfernt.
14:09 Uhr
Des sind übrigens auch genau die, die nicht abschließen konnten! ("unvollständige Antwort") (bearbeitet) 

48 haben nur eine Antwort angekreuzt, die lasse ich natürlich drinnen, wäre interessant die auch mal separat auszuwerten!

bei einem n von >1200 wohl die bisher weltweit größte Untersuchung diesbezüglich!
image.png 
image.png


14:17 Uhr
kosten sind weit hinten, Förderung in Österreich unerheblich - kannst gut in deiner Arbeit diskutieren!

Hannes  14:18 Uhr
dh. ich kann gut diskutieren, dass meine Arbeit uninteressant für ImkerInnen ist :zwinkern:

Robert Brodschneider  14:20 Uhr
nene, Kosten spielen für die Imker bei der Wahl der Behandlungsmethode keine Rolle, das ist a) gut so, weil teuer nicht gleich gut ist (bearbeitet) 
14:20 Uhr
b) falsch, weil teuer gut ist!
14:20 Uhr
Zutreffendes basierend auf deiner Endaussage ankreuzen!

Hannes  14:20 Uhr
nice :zwinkern:
Neu

Robert Brodschneider  14:21 Uhr
Die Topp 5 Gründe sind alle sehr sachlich, und können durch haufenweise studien in der Diskussion belegt werden!
14:22 Uhr
Gewohnheit spielt eine erstaunlich kleine Rolle, was zeigt, das Imkereien gewillt sind flexibel zu reagieren
14:23 Uhr
Ein Ö Spezifikum scheint, dass Rückständen soviel mehr Beachtung geschenkt wird als Resistenzen!

Hannes  14:23 Uhr
weißt du ob die Reihenfolge der 5 Gründe wie du sie exportierst, dass “klick” Verhalten widerspiegelt. Also erster Grund wurde als erstes geklickt etc. oder einfach nur von der random Reihenfolge kommt.

Robert Brodschneider  14:24 Uhr
nene, das wäre so nicht möglich, da ja jeder eine andere Reihenfolge gesehen hat, und die Ausgabe in einer einheitlichen Tabelle erfolgt!
14:24 Uhr
deswegen sag ich ja, nur mal die 1-klicker auswerten!

Hannes  14:24 Uhr
jo auf jeden Fall




# Treatment


 We use normal parameters, same results as with lm
 ~ 0 to check not between groups
 https://www.researchgate.net/post/R_stats_It_is_possible_to_fix_the_intercept_of_a_GLS_model_with_both_categorical_and_continuous_predictors
 https://stats.stackexchange.com/questions/181113/is-there-any-difference-between-lm-and-glm-for-the-gaussian-family-of-glm
 https://stats.stackexchange.com/questions/190763/how-to-decide-which-glm-family-to-use
 Poisson Info
 http://www.stat.cmu.edu/~brian/463-663/week04/checking-poissonness.pdf
 https://www.theanalysisfactor.com/generalized-linear-models-in-r-part-6-poisson-regression-count-variables/
 lmer package
 file:///Users/btree-mac/Downloads/v82i13.pdf

## Mixed Model

Generate Mixed Model to check if factor treatment type is relevant for costs.


# Links

- Science Forum: Ten common statistical mistakes to watch out for when writing or reviewing a manuscript
  - https://elifesciences.org/articles/48175
- What is the difference between fixed effect, random effect and mixed effect models?
  - https://stats.stackexchange.com/questions/4700/what-is-the-difference-between-fixed-effect-random-effect-and-mixed-effect-mode
- Check Your Residual Plots to Ensure Trustworthy Regression Results!
  - https://statisticsbyjim.com/regression/check-residual-plots-regression-analysis/
- ANOVA 
  - http://homepages.inf.ed.ac.uk/bwebb/statistics/ANOVA_in_R.pdf
- Varianzanalyse
  - https://www.beratung-statistik.de/statistik-beratung-infos/r-tutorial/r-varianzanalyse-post-hoc/


